### ISSUE TITLE
abs-

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#31]
The following hyphenation points are missing when using the liturgical patterns:
ab-stare, ab-sto, abs-tentus (from abstineo), ab-stiti (from absisto)

The following hyphenation points are incorrect:
absu-mpsi, absu-msi, absu-mptus (all from absumere)

**Comment by fradec** [comment]
All of the words beginning with `abs` are also to be proofread for hyphenation `abs-` or `ab-s`. It should be quite simple because there are only about 130 words concerned (at least the roots, which must be declined or conjugated).

This can be done soon (I'll have time at the end of next week, I hope).

**Comment by fradec** [comment]
All seems correct now for me. Close if it's ok for you.
