### ISSUE TITLE
hyphen-la demo gives caelis three syllables.  The latin dictionary says its just two.

### ISSUE THREAD

**Issue by jacknickles** [gregorio-project/hyphen-la#48]
I would assume caelis (of all the words to not get right) is correct, but the dictionary shows the pronunciation having two syllables.   jack.richard.nickles@emory.edu  hyphen-la shows 3.

**Comment by fradec** [comment]
Of course there are only 2 syllables for the Latin word `cælis`. But it is normal that the demo gives three syllables for `caelis` because the characters `a` and `e` are not written as a ligature `æ` as they should be in liturgical Latin. For the script of the demo, enter a correct Latin typography because it will not correct them itself, fortunately by the way: `aeris` (`aer`, `aeris`: the air), 3 syllabes, is not the same thing as `æris` (`æs`, `æris`, the bronze), 2 syllabes.
