### ISSUE TITLE
potuere

### ISSUE THREAD

**Issue by fradec** [gregorio-project/hyphen-la#6]
The word potuere (from "possum"), should be hyphened like this:

> pot-u-e-re

but for now it's

> po-tu-e-re.

I'm not very good at modifying the patterns in order to obtain the good result, @eroux  can you tell me how to do this?

**Comment by OldClaudio** [comment]
It is true that the adjective potis is used together with the verb sum 
to indicate the same concept of the verb possum. For example potis es = 
potes; potis sunt = possunt; etc.; even in interrogative phrases as in 
potin es = potesne; potin ut = potestne ut; etc.

But this is not a good reason to consider the verb possum as composed 
with pot+sum with assimilation in some forms for the verbal root with 
the "désinence" (apparently in English there is no single word to 
indicate the endings of the verb conjugation, at least I could not find 
any). I this were true, then the present tense should hyphenate as this:
pos-sum
pot-es
pot-est
pos-su-mus
pot-es-tis
pos-sunt
wihich is evidently wrong in the forms where the désinence starts with a 
vowel.

In the specific case of preteritum, pot+fui -->potui had a different 
kind of assimilation and again if this were true it whole preteritum 
should hyphenate as

pot-u-i
pot-u-is-ti
pot-u-it
pot-u-i-mus
pot-u-is-tis
pot-u-e-runt
and potuere means the same as potuerunt but the accent/accent is different.

But again we are in a similar case as languere (infinitive) and languere 
(pretritum) where long and short vowels make the difference in 
pronuonciation and in this case also in hyphenation.

In the case of potuere and potuerunt the long and short vowerls should 
be respectively potūĕre and potuēre, but in both cases the prosodic 
syllables don't change, and both should hyphenate as po-tu-e-re.

But, Frère Arnaud, as I have always said, I am just a "vilis 
mechanicus"; I can program patterns, but I am everithng but a latinist. 
What does your LAtin professor say on this subject?

Therefore you have two choices: you can
1) leave things as they are, or
2) add a new pattern to the list:

.po4t3uere.

(the dots are included). You can add it in any position, because the 
pattern sorting has no influence on their meaning. The fact that they 
are sorted, is handy only for the programmer.

Best regards
Claudio

**Comment by fradec** [comment]
Thank you Claudio for your usual precision!
But for us, the following list is correct:
> pos-sum pot-es pot-est pos-su-mus pot-es-tis pos-sunt

and you can find in proofreading-Solesmes-1.txt at line 303-308 what we're expecting for (and also in phonetic-rules.md line 18), note that we have pot-e-rit and no po-te-rit.

For us, the hyphenation pot-u-e-re is in the continuity (as for all the forms of the verb in fact).
In the case of pot*, it's the famous case of "sentiment étymologique" wich justifies "surprising" hyphenations. My latin Professor supports this point (to be more true, it is rather he who holds it, and I support him!)
That's why I asked to modify the patterns, but I want your agreement before doing so. The "vilis mechanicus" has a point of view which interests me!

Sorry for my bad English, I hope this is clear anyway.

**Comment by OldClaudio** [comment]
Dear Frère Arnaud,
your English is very clear.

In this case, the patterns to add to the pattern list are not just one, 
the one I wrote you in my previous message, but some 20 ones, at least; 
not so simple to set up in order to get the desired hyphenation for the 
forms of the conjugation of the verb possum, without ruining the 
hyphenation of many other words that have nothing to do with possum.

The maintainer of the Latin hyphenation pattern files is now Élie Roux. 
I gave up; our common friend Èlie knows why. If Élie can mange this 
actual hyphenation problem by himself, it's fine; if he asks my support 
is also fine; in the past few months we cooperated very well with one 
another. He read this message in the mailing list.

In spite of the etymological sentiment, I wonder how you adapt that 
hyphenation type to singing the gregorian chants; I already expressed my 
opinion about the fact that "syllable" is a fuzzy concept, because 
grammar, common speech, emphatic speech, singing, just to name a few, 
are different concepts on which different scholars have different views 
-- forgive my repeating the word "different", but it emphasizes the pint.

All the best
Claudio

**Comment by eroux** [comment]
@fradec can you please copy paste here a complete list of all conjugated forms of possum with hyphens? Or you can add them directly in one of the tests, then once it's in a test I can easily build the needed patterns and give you a small explanation so that you can add more in the future (but the work flow is always to add tests first)

**Comment by fradec** [comment]
Ok, @eroux, I've pushed it yesterday in proofreading-Solesmes-1.

**Comment by eroux** [comment]
Ok, next step is for you to be able to run the tests, can you run the
python file?
-- 
Élie
